In [29]:
#Johannes Sesselmann
#Antony
#Paulo Kuga

In [30]:
import numpy as np
import pandas as pd

In [31]:
from google.colab import drive #conectar no drive(onde os dados estão)
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [32]:
df_treino = pd.read_csv("/content/drive/Shareddrives/Mecdata/Projeto/Tweets/train.csv") #acessar o drive
df_treino.head() #análise inicial dos dados treino

textID  ... sentiment
0  cb774db0d1  ...   neutral
1  549e992a42  ...  negative
2  088c60f138  ...  negative
3  9642c003ef  ...  negative
4  358bd9e861  ...  negative

[5 rows x 4 columns]

In [33]:
df_teste = pd.read_csv("/content/drive/Shareddrives/Mecdata/Projeto/Tweets/test (1).csv")
df_teste.head() #análise inicial dos dados teste

textID                                               text sentiment
0  f87dea47db  Last session of the day  http://twitpic.com/67ezh   neutral
1  96d74cb729   Shanghai is also really exciting (precisely -...  positive
2  eee518ae67  Recession hit Veronique Branquinho, she has to...  negative
3  01082688c6                                        happy bday!  positive
4  33987a8ee5             http://twitpic.com/4w75p - I like it!!  positive

In [34]:
len(df_treino)

27481

In [35]:
df_treino.isnull().sum() #um dos dados parece ser zero ou outlier

textID           0
text             1
selected_text    1
sentiment        0
dtype: int64

In [36]:
df_treino = df_treino.dropna() #vamos excluir essa linha pois um dado a menos não nos faz falta

In [37]:
df_treino.isnull().sum() #analisando para ver se funcionou

textID           0
text             0
selected_text    0
sentiment        0
dtype: int64

In [38]:
from sklearn.model_selection import train_test_split #criação do split da nossa máquina

X = df_treino['selected_text']
y = df_treino['sentiment']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0) #decidimos deixar 20% dos dados para teste e 80% treino

In [39]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC

sentiment_clf = Pipeline([('tfidf', TfidfVectorizer()), #criação de uma pipeline para facilitar o processo
                        ('clf', LinearSVC()),])

#treinamento da pipeline
sentiment_clf.fit(X_train, y_train) 

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', LinearSVC())])

In [40]:
#forma de predição
predictions = sentiment_clf.predict(X_test)

In [41]:
from sklearn import metrics

#print geral para ver desempenho da IA
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

    negative       0.81      0.78      0.80      1523
     neutral       0.81      0.87      0.84      2275
    positive       0.88      0.83      0.85      1698

    accuracy                           0.83      5496
   macro avg       0.83      0.83      0.83      5496
weighted avg       0.83      0.83      0.83      5496



In [42]:
#Print da matriz de confusão

print(metrics.confusion_matrix(y_test,predictions))

[[1188  275   60]
 [ 169 1969  137]
 [ 101  188 1409]]
